//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Spectronic.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MAIN_DEFAULT                101
#define IDD_SPECTRONIC_DIALOG           102
#define IDD_CONFIGURATION_DIALOG        103
#define IDD_MAIN_BLANK                  104
#define IDD_CONFIG_COMPORT              105
#define IDD_MAIN_SCAN                   106
#define IDD_MAIN_INFO                   107
#define IDD_FULLGRAPHDLG                108
#define IDD_MAXDLG                      109
#define IDD_MAIN_GRAPH                  110
#define IDR_MAINFRAME                   128
#define IDI_ICON                        131
#define IDR_MENU                        132
#define IDR_TOOLBAR                     132
#define IDD_MAINCOMMANDS                138
#define IDD_MAIN_COMMANDS               138
#define IDC_TEST                        1001
#define IDC_BUTTON1                     1002
#define IDC_SENDCOMMAND                 1002
#define IDC_UVSCAN                      1002
#define IDC_SEL                         1002
#define IDC_SAVE                        1002
#define ID_ToSend                       1003
#define IDC_AJOUTER                     1003
#define IDC_COMPORT                     1004
#define IDC_EDIT_2                      1005
#define IDC_EDIT_BaudRate               1005
#define IDC_STRING                      1006
#define IDC_EDIT_3                      1006
#define IDC_EDIT_ByteSize               1006
#define IDC_EDIT_4                      1007
#define IDC_EDIT_Parity                 1007
#define IDC_ERROR                       1008
#define IDC_EDIT_5                      1008
#define IDC_EDIT_StopBits               1008
#define IDC_INITIALYSE                  1009
#define IDC_Tesht                       1010
#define IDC_TREE_OPTIONS                1015
#define IDC_STATIC_OPTIONS              1016
#define IDC_Com_Options                 1016
#define IDC_STATIC_1                    1018
#define IDC_STATIC_2                    1019
#define IDC_STATIC_3                    1020
#define IDC_EDIT_1                      1021
#define IDC_EDIT_ComPort                1021
#define IDC_STATIC_4                    1022
#define IDC_STATIC_5                    1023
#define IDC_LIST1                       1023
#define IDC_LOG                         1023
#define IDC_VALUE                       1023
#define IDC_LIST2                       1024
#define IDC_LISTLOG                     1024
#define IDC_LIST                        1024
#define IDC_MENU                        1025
#define IDC_WORKSPACE                   1026
#define IDC_COMMAND                     1036
#define IDC_CANCEL                      1038
#define IDC_CANCELER                    1038
#define IDC_PATH                        1041
#define IDC_NOM                         1042
#define IDC_BROWSE                      1043
#define IDC_DELETE                      1045
#define IDC_BUTTON2                     1048
#define IDC_ADD                         1048
#define IDC_DEFAULT                     1048
#define IDC_MAX                         1048
#define IDC_INC                         1049
#define IDC_NB                          1050
#define IDC_SPEED                       1050
#define IDC_STRTWV                      1051
#define IDC_PARITY                      1052
#define IDC_STOPWV                      1052
#define IDC_TIME                        1053
#define IDC_BYTESIZE                    1055
#define IDC_GRAPH                       1055
#define IDC_PIQUES                      1056
#define IDC_XY                          1057
#define IDC_ACCEPT                      1059
#define IDC_STOPBITS                    1060
#define IDC_XMIN                        1060
#define IDC_BEGIN                       1060
#define IDC_BAUDRATE                    1061
#define IDC_XMAX                        1061
#define IDC_END                         1061
#define IDC_YMIN                        1062
#define IDC_MAXIMUM                     1062
#define IDC_XUP                         1064
#define IDC_XAUTOMATIC                  1065
#define IDC_XUS                         1066
#define IDC_YMAX                        1067
#define IDC_YUP                         1068
#define IDC_YUS                         1069
#define IDC_YAUTOMATIC                  1070
#define IDC_BACK                        1071
#define IDC_DEFAULTCOLORS               1072
#define IDC_DROITE                      1073
#define IDC_GRADS                       1074
#define IDC_TITLE                       1077
#define IDC_STUDENT                     1078
#define IDC_GROUP                       1079
#define IDC_DATE                        1080
#define IDC_SUBST                       1081
#define ID_FICHIER_OUVRIRUNPROJET       32771
#define ID_FICHIER_SAUVEGARDERSOUS      32772
#define ID_FICHIER_SAVEPROJECT          32772
#define ID_FICHIER_QUITTER              32776
#define ID_FICHIER_SAUVEGARDER          32777
#define ID_FICHIER_NOUVEAUPROJET_GRAPHIQUE 32778
#define ID_FICHIER_NOUVEAUPROJET_PARAMTREDINITIALIZATION 32779
#define ID_FICHIER_NOUVEAUPROJET_SPECTREUV 32780
#define ID_FICHIER_NOUVEAUPROJET_SPECTREVISIBLE 32781
#define ID_TOOL_NEW                     32782
#define ID_TOOL_OPEN                    32783
#define ID_TOOL_SAVE                    32785
#define ID_TOOL_PRINT                   32786
#define ID_TOOL_PRINTPREVIEW            32787
#define ID_TOOL_PASTE                   32789
#define ID_TOOL_COPY                    32790
#define ID_TOOL_CUT                     32792
#define ID_EDITION_OPTIONS              32793
#define ID_AIDE_PROPOS                  32794
#define ID_FICHIER_SAVEDATA             32797
#define ID_FICHIER_ENREGISTRER_SAVEGRAPH 32798
#define ID_FICHIER_SAVEGRAPH            32798
#define ID_FICHIER_OPENDATA             32799
#define ID_FICHIER_OPENPROJECT          32800
#define ID_FICHIER_OPENGRAPH            32801
#define ID_OUTILS_SOUSTRAIRE            32802
#define ID_FICHIER_SAVEETALON           32803
#define ID_FICHIER_OPENETALON           32804
#define ID_FICHIER_SAVEDATA_BIN         32805
#define ID_FICHIER_OPENDATA_BIN         32806
#define ID_FICHIER_OPENTXT_VIRG         32807
#define ID_FICHIER_OPENTXT_TAB          32808
#define ID_FICHIER_OPENTXT_PTVRIG       32809
#define ID_FICHIER_SAVETXT_VIRG         32811
#define ID_FICHIER_SAVETXT_TAB          32812
#define ID_FICHIER_SAVETXT_PTVIRG       32813
#define ID_FICHIER_OPEN_TXT             32814
#define ID_FICHIER_SAVE_TXT             32815
#define ID_FICHIER_PRINT                32816

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32817
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
